_SEVERITY_EMOJI = {
    "critical": "❌",
    "warning": "⚠️",
    "suggestion": "💡",
}

_SEVERITY_ORDER = {"critical": 0, "warning": 1, "suggestion": 2}


def format_issue_comment(issue: dict) -> str:
    """Format a single issue dict into a GitHub comment block.

    Expected issue keys: severity, title, description, line (optional), filename (optional)
    """
    severity = issue.get("severity", "suggestion").lower()
    emoji = _SEVERITY_EMOJI.get(severity, "💡")
    title = issue.get("title", "Issue")
    description = issue.get("description", "")

    lines = [f"{emoji} **{title}**"]
    if description:
        lines.append(f"\n{description}")
    if issue.get("filename"):
        loc = issue["filename"]
        if issue.get("line"):
            loc += f":{issue['line']}"
        lines.append(f"\n_Location: `{loc}`_")

    return "\n".join(lines)


def format_summary_comment(iteration: int, issues: list[dict]) -> str:
    """Format a full PR summary comment for a given review iteration."""
    sorted_issues = sorted(issues, key=lambda i: _SEVERITY_ORDER.get(i.get("severity", "suggestion").lower(), 2))

    counts: dict[str, int] = {"critical": 0, "warning": 0, "suggestion": 0}
    for issue in sorted_issues:
        sev = issue.get("severity", "suggestion").lower()
        if sev in counts:
            counts[sev] += 1

    header = (
        f"## SLM Review — Iteration {iteration}\n\n"
        f"| ❌ Critical | ⚠️ Warning | 💡 Suggestion |\n"
        f"|:-----------:|:----------:|:-------------:|\n"
        f"| {counts['critical']} | {counts['warning']} | {counts['suggestion']} |\n"
    )

    if not sorted_issues:
        return header + "\nNo issues found. Looks good!\n"

    sections: list[str] = [header]
    for issue in sorted_issues:
        sections.append("---\n" + format_issue_comment(issue))

    sections.append("\n---\n_Review generated by [github-slm-reviewer](https://github.com) using a local SLM._")
    return "\n".join(sections)
